version: "3.9"
services:
  webapp:
    image: mahejose2020/webapp-jenkins:v1
    ports: ["80:1200"]
    environment:
      PORT: 1200
  testapp:
    image: crccheck/hello-world
    ports: ["7070:8000"]
    