---
- name: Remove the welcome file from the user's home
  hosts: local
  gather_facts: false
  vars:
    new_username: "courseuser"
    dest_file: "/home/{{ new_username }}/welcome.txt"
  tasks:
    - name: Ensure the welcome file is absent
      ansible.builtin.file:
        path: "{{ dest_file }}"
        state: absent
