
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  FEATURE_IMAGE_UPLOAD: "true"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "your-bucket-name"
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_ME"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
